title: 仇杰
description: 我的个人博客
author: 仇杰
logo: /static/img/avatar.png
github: https://github.com/qiujayen
about: Android developer

baseurl: "https://qiujayen.github.io"
url: "https://qiujayen.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
